### ISSUE TITLE
Support forked blockchains such as Flax Network

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#105]
Requests are coming in to offer a Machinaris image which works for other blockchains, forked off the main Chia blockchain.

Some examples:

- https://flaxnetwork.org/
- https://github.com/felixbrucker/chia-blockchain
- https://www.chaingreen.org/

Questions:

1. Could this be a single image with different folders for blockchains, where Docker env variable determines which is started?
2. What happens if the forked blockchain no longer is CLI/API comaptible?
3. Would it be possible to have more than one blockchain farming the same plots at once?

**Comment by guydavis** [comment]
Current workaround for Unraid users posted in our Discord: "Share the plots directory from Unraid to a Windows VM via SMB and run the Flask (or other) clients there."

**Comment by jollyjollyjolly** [comment]
I can answer 3. Would it be possible to have more than one blockchain farming the same plots at once?

Yes I have FLAX and Chaingreen and Chia plots running (chia farming via hpool)

And give a guess to number 2. What happens if the forked blockchain no longer is CLI/API comaptible?

They are a goodways off breaking in any major way fashion, however possibly some commands (name changes) do appear to be a thing. Not really breaking, but name convention.

**Comment by guydavis** [comment]
[Flax support](https://github.com/guydavis/machinaris/wiki/Flax) is now feature complete in test version: ghcr.io/guydavis/machinaris:test  Will be released to final shortly.

**Comment by guydavis** [comment]
Closing as [v0.5.0](https://github.com/guydavis/machinaris/releases/tag/0.5.0) is released now.  Will stick with Flax support only for now.
