### ISSUE TITLE
Automatic pruning of non-portable plots

### ISSUE THREAD

**Issue by ryan-haver** [guydavis/machinaris#144]
With official support for pools arriving shortly, most users will start creating portable plots that can be used to farm with pools. 

It would be ideal to have a way to automatically prune non-portable plots. I can think of a bunch of different ways to handle this behavior. At the highest level it seems most logical for the general workflow to be as outlined below.

Workflow:
1. User specifies to create Portable Plots
2. User defines if they want to enable pruning a non-portable plot each time portable plot is successfully created
3. Now as new portable plots are created the old non-portables will in effect be replaced.
4. Rejoice that you don’t have to manage your storage because it has been automated.

**Comment by guydavis** [comment]
I'm looking forward to this [feature being available in Plotman](https://github.com/ericaltendorf/plotman/pull/870) soon.

**Comment by HitLuca** [comment]
Any update on this? Would a feature where old non-portable plots can be automatically replotted be feasible in machinaris?

**Comment by guydavis** [comment]
Closing as stale at this point.

**Comment by guydavis** [comment]
Re-opening to implement this in Machinaris itself, rather than down in Plotman.  Current settings on the Farming page in the development stream.

![Screenshot from 2022-11-17 21-38-52](https://user-images.githubusercontent.com/12936/202928482-c317f625-e7b6-453a-aff2-166d582cb98e.png)

Machinaris will just delete a few old plots per plot directory until adequate free space is present.  Plotting (and optionally archiving) will then recognize the available space and plot into it, using your latest plotting configuration.

**Comment by guydavis** [comment]
This is now in the `machinaris:test` images.  Will be in the [upcoming v0.8.6 release](https://github.com/guydavis/machinaris/wiki/Releases).
