### ISSUE TITLE
Pool menu show SELF_POOLING while Pooling settings show FARMING_TO_POOL

### ISSUE THREAD

**Issue by cmbcbe** [guydavis/machinaris#269]
Hello,

perhaps a GUI issue but using machinaris 0.54, when i click my "POOL3 menu, it show my pool with status "SELF_POOLING" while on the settings page, pooling, this pool show as "FARMING_TO_POOL"
All the systems seems to really farm to the pool, on the Summary page, i see some little points popping on the graph.

**Comment by guydavis** [comment]
Sorry to hear that.  Please provide (redacted) screenshots showing:

1. Settings | Pools page
2. Pools page
3. Output of `chia plotnft show` from an in-container shell (`docker exec -it machinaris bash`)

Thanks!

**Comment by cmbcbe** [comment]
Hello,

here it is:
![image](https://user-images.githubusercontent.com/21077157/132494684-b360243d-bded-474b-9049-d7b7fead3497.png)

![image](https://user-images.githubusercontent.com/21077157/132494777-0318fa07-4bc3-4020-ae0e-4c963614a7d8.png)

![image](https://user-images.githubusercontent.com/21077157/132494995-c8dbcc81-e7cb-4678-a97c-3ad025d42a15.png)

As you can see, both in-container shell and settings menu show "FARMING TO POOL" while Pools menu show "SELF POOLING" for the same contract and launcher ID

**Comment by guydavis** [comment]
Hi, sorry for the delay.  I was helping another user with a similar issue and we found this [issue report](https://github.com/Chia-Network/chia-blockchain/issues/7210).  After removing stopping Machinaris, removing his ~/.machinaris/mainnet/wallet folder, then starting up Machinaris and waiting a day for the Wallet to re-sync, the problem was resolved for him.  Please give this a try in your case too.

**Comment by guydavis** [comment]
Hi, any update on whether the solution above got Machinaris reset into a better state?

**Comment by guydavis** [comment]
Latest version is 0.5.6.  Please update when you get a chance.  Thanks!
