### ISSUE TITLE
plotting tmp output incorrect.

### ISSUE THREAD

**Issue by zer0ed** [guydavis/machinaris#40]
When looking at plot jobs, the first tmp should list the plotting directory used (as seen in the plotman cli output) and not the temp plot size.  Temp plot size is found on the second tmp column.

![image](https://user-images.githubusercontent.com/8206700/119212755-6a7fa180-ba88-11eb-98c0-c828c2565063.png)

**Comment by guydavis** [comment]
Great catch! I see that Plotman duplicates its column names.  I've renamed the 2nd column display to `size`.  Fixed in development.  Will hit test branch in a day or so.  Released later this week.  Thanks for the report!

![image](https://user-images.githubusercontent.com/12936/119274346-acb1fb80-bbcc-11eb-82e5-d851a5f4261d.png)
