### ISSUE TITLE
prune of zombie nodes during dust storm

### ISSUE THREAD

**Issue by mdrummer68** [guydavis/machinaris#517]
Digital Spaceport found a script on [SpaceFarmer.io's](https://discord.com/channels/844266352213622855/891986374717243403/922563772286111834) developer channel that disconnects zombie nodes falling behind by so many blocks.  I used the script with good success and didn't fall out of sync at all this time.  It may help others if you incorporate it into your future builds with a method to trigger it.

`curl -s --insecure --cert ~/.chia/mainnet/config/ssl/full_node/priva
te_full_node.crt --key ~/.chia/mainnet/config/ssl/full_node/private_full_node.key -d '{}' -H "Content-Type: application/json" -X POST https://localhost:8555/get_connections | jq -r '.connections | map(select(.peak_height)) as $C | [$C[].peak_height] | max as $H | $C | map(. + {lag: ($H - .peak_height)}) | .[] | select(.lag > 15) | .node_id[2:10]?' | xargs -n1 chia show -r`

As always, thank you for the great work.

**Comment by guydavis** [comment]
Thanks for the suggestion.  I will look at this when I get a chance.

**Comment by k2skaterii** [comment]
@mdrummer68  - Apologies up front, I've disagree with you on this one.  

Intentionally disconnecting connections from other nodes that are unable to keep up with the blockchain or are falling behind for 1 reason or another - is "A Dick Move".
1.  If your node is caught up, connections from nodes that have fallen behind are not hurting you.
2.  If everyone disconnected sessions from nodes that are falling behind - those nodes will never sync back up with the blockchain.  
3.  If disconnecting these sessions was actually good the the CHIA Network, why isn't this functionality built into the official Chia distributions?

During the October / November dust storms, I monitored my connections and their block heights.  What I saw was 15% - 25% of the connections were falling behind.  My node wasn't impacted, but I was concerned that I may fall behind if that number continued to climb.  

Instead of disconnecting nodes that were struggling... I adjusted my node's config.yaml to allow for more total connections and more outbound connections.  
```
full_node:
  target_outbound_peer_count: 16 (Default is 8)
  target_peer_count: 120 (Default is 80)
```

If your node is able to keep up during a dust storm, your chances of finding a block go up thanks to the UN-synced nodes essentially being offline.  That doesn't mean we need to intentionally prevent those nodes from catching up.

- Ken

**Comment by guydavis** [comment]
> but the issue is that these settings seem to get overwritten each time Machinaris either is restarted or upgraded.

Sorry, the `target_peer_count` is controlled by [Forktools](https://github.com/guydavis/machinaris/wiki/Forktools) within the container.  Assuming you are on Unraid, the configuration file is `/mnt/user/appdata/machinaris/forktools/ftconfig/config.forkfixconfig` as SETFNTARGETPEERCOUNT.  Edits there are applied on each container restart.

FYI, in next release (already in `:develop` and `:test` images), there is a "Settings | Tools" page allowing direct configuration thru the WebUI:

![image](https://user-images.githubusercontent.com/12936/150817913-2c507ce8-33d7-4af4-a503-f2f7b1e55360.png)

**Comment by gibblinhimer** [comment]
I gave this a shot and this is pretty cool.. but i am having some confusion and the docs do seem to be clear..

the SETTARGETPEERCOUNT  for fork tools being equal to the target_peer_count setting in the Chia config.yaml file is easy to understand :)
but i would also like to set the "target_outbound_peer_count" in the config.yaml file..

i tried "SETFNTARGETOUTBOUNDPEERCOUNT" but that did not seem to work.... how do i find out what setting in the chia config.yml  maps to ??? in the fork tools config.. or if even all setting are supported?

**Comment by guydavis** [comment]
> i tried "SETFNTARGETOUTBOUNDPEERCOUNT" but that did not seem to work.... how do i find out what setting in the chia config.yml maps to ??? in the fork tools config.. or if even all setting are supported?

Yes, it looks like the author of [Forktools](https://github.com/Qwinn1/forktools) didn't add support for modifying that particular setting (Machinaris WebUI - Settings | Tools page), so it will be editable in the blockchain's config.yaml (Machinaris WebUI - Settings | Farming page).  Both Settings pages have their respective config files showing what can be edited.  Apologies for the inconsistency.

**Comment by mdrummer68** [comment]
> @k2skaterii
Intentionally disconnecting connections from other nodes that are unable to keep up with the blockchain or are falling behind for 1 reason or another - is "A Dick _Move".

No offense taken.

The December 20 and 28 dust storms, which had mempool spikes of 12k, were the ONLY events worthy of using the script in my opinion.  Unfortunately, increasing peers did not work for me.  Every situation is different, therefore having tools to deal with the situation is a plus in my book.

Sorry if I disconnected your node using this script. 😄
