### ISSUE TITLE
Support farmer(+wallet) mode for Machinaris, pointing to a remote full-node.

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#747]
Good suggestion from the Discord.  Requires some research to evaluate the implications.

![image](https://user-images.githubusercontent.com/12936/184433116-7d01b689-8706-4c9b-9c4e-86efa7f63157.png)

**Comment by Yamanipanuchi** [comment]
Just for reference, This is the process I got through to point a friends farmer to my fullnode.

`farmer:
  full_node_peer:
    host: 127.0.0.1 <--- Change this to my DNS or IP.
    port: 8444`

Optionally, I change this also as they might as well use my DB for their wallet also.

`wallet:
  full_node_peer:
    host: 127.0.0.1 <--- Change this to my DNS or IP.
    port: 8444`

Then run the following.
`chia start farmer-only
chia start wallet`

If they have a harvester on that system also then I also run
`chia start harvester`

This ultimately frees them up from having to have there own Blockchain DB. They do the `chia stop all` and specific start up each time they start the container.

**Comment by Yamanipanuchi** [comment]
So I've had a buddy connect to my DB for a few weeks now. He confirmed it works, But he confirmed by looking at the logs and seeing proofs pass thru his harvester.

Turns out the web UI seeing the chain offline this way. So this would indicate something else would need to be modified for Machinaris to see the system as online.

**Comment by guydavis** [comment]
Sorry, I don't think I'll be able to support and maintain this configuration.
