### ISSUE TITLE
Not plots shown under farming

### ISSUE THREAD

**Issue by grobalt** [guydavis/machinaris#763]
Everything is running fine, fresh machinaris install, changing from bare metal to docker environment, but the large node is not showing the plots.

![1](https://user-images.githubusercontent.com/79084968/189287290-55a641bd-8dfa-40e7-a36c-80c2b3a312c8.PNG)
![2](https://user-images.githubusercontent.com/79084968/189287293-99a3ae91-b0bd-4d93-9844-829495e20c70.PNG)
![3](https://user-images.githubusercontent.com/79084968/189287296-c0e6a731-e73b-42ca-98dd-2b2d1f14d113.PNG)

**Comment by grobalt** [comment]
Which log can i provide for you ? :)

**Comment by guydavis** [comment]
Hi, this can happen when you have duplicated plots, but other causes are possible.  Please share a few configurations including your `docker-compose.yml` and all details of your OS, etc.

Then please share the output of `chia farm summary` from a shell [inside the container](https://github.com/guydavis/machinaris#container-cli). Then also provide the [Server Log](https://github.com/guydavis/machinaris/wiki/Troubleshooting#where-are-the-logs)  (aka apisrv.log) from the Machinaris controller.

**Comment by guydavis** [comment]
Okay, thanks for that log output.  I've just enabled some additional debugging in the `:develop` image so please try switching from `:latest` to `:develop` in your `docker-compose.yml` and [run that](https://github.com/guydavis/machinaris/wiki/Releases#upgrading), watching for log output in the apisrv.log about duplicated plots on the same host.

**Comment by grobalt** [comment]
i did and startet - takes a while with that number of plots.
checking the server console i see this:
![image](https://user-images.githubusercontent.com/79084968/189420088-3d8a8a3f-6279-4d63-aadd-2b99dc4628aa.png)

As the server has tons of memory, is this maybe a docker config issue, not enough memory on the container ? Dual 64 core Epyc and 256GB memory

**Comment by grobalt** [comment]
After a reboot of the machine (just to make sure all memory is free) - same problem as after the fresh install. The plots are not loaded and it just stops somewhen and does not farm. It took several container restarts last time to be succesful farming. Bare metal installation was without that issue.

[apisrv.log](https://github.com/guydavis/machinaris/files/9538053/apisrv.log)

**Comment by guydavis** [comment]
Sure, given the number of plots you have (over 100k) let's narrow the scope of the problem down rather than trying to load everything at once.  Please edit your `docker-compose.yml` to remove most of the Volumes listed above, start with just one Volume initially.  Then restart the container, monitor with `docker stats` from Host OS, and then:

1. **Wait at least 15 minutes** for the container after launch to get running smoothly.
1. Check that `chia farm summary` is correct for those Volumes mounted.  Run that command inside the container.
1. Verify that Farming page lists those plots and that total count on table, matches `farm summary`.
1. Edit your `docker-compose.yml` to add a few more Volumes, restart the container and go back to step 1 above.

Repeat this process, incrementally adding more drives and plots, watching memory usage via `docker stats`.  This way we can see if there is a memory issue at some point. Please see the wiki for more details on [scaling Machinaris](https://github.com/guydavis/machinaris/wiki/Scaling) to that many plots.

**Comment by grobalt** [comment]
i reduced to just one plot folder and issue is the same
[apisrv.log](https://github.com/guydavis/machinaris/files/9538983/apisrv.log)
[apisrv-part2.log](https://github.com/guydavis/machinaris/files/9538984/apisrv-part2.log)

**Comment by guydavis** [comment]
Alright, in the 20 lines of logs you provided in your last, I find no issue.  At this pace we could be corresponding for days which will be frustrating for you.  When very large farmers such as yourself have needed assistance in the past, I have offered remote sessions on our Discord via TeamViewer.  Let me know on [Discord](https://discord.gg/mX4AtMTt87) if you are interested. 

I'd like to get a better picture of your setup as your Unraid post refers to another Unraid system as fullnode, yet you are also running another fullnode on Linux (?).  Hopefully an in-person session would let me understand why you're not using [workers](https://github.com/guydavis/machinaris/wiki/Workers).

**Comment by grobalt** [comment]
thanks for the offering, will do this soon.
The unraid installation was my small one at home / the 16PB farmer is in the datacenter ;)

**Comment by guydavis** [comment]
Hi!  If you are still running Machinaris in your data center, please try the latest `machinaris:develop` which makes use of bulk record insert for plot status.  I've also instrumented memory usage logging in this section of the code.  

![image](https://user-images.githubusercontent.com/12936/190870357-cc83a30c-1ea9-46f1-a55a-d0137a119aa7.png)

Looking forward to your feedback.

**Comment by grobalt** [comment]
Thanks for the hint -  i just restartet the container to pull the new version.

**Comment by guydavis** [comment]
Hi! I created a test harness to simulate storing 120000 plot status records into the Sqlite3 database at `/root/.chia/machinaris/dbs/plots.db`.  I'll never have a farm this big, but my test harness simulates tracking that many plots, similar to your farm.  This "full insert" only happens on launch and infrequently thereafter, with most status updates only looking for newly arrived plots (by recent time).  

![image](https://user-images.githubusercontent.com/12936/190930508-2d540a2a-4546-4374-ac30-33657de1d3d8.png)

I found that the full batch insert of that many rows took one minute and used, at peak, just over 500 MB of memory (in that Machinaris Python process).  The `plots.db` file did grow to 25 MB on disk after a few tests.  This test was done on my old HP tower (nearly 10 years now) with a cheap SATA SSD.

Due to the server-side data table paging, the Farming page of Machinaris WebUI then loaded in a just a couple of seconds.  Filtering and paging forward were also a few seconds to complete.  

![image](https://user-images.githubusercontent.com/12936/190930716-f5d20f87-419e-4f50-a38c-e8c7072fcbaf.png)

Thanks again for pushing me to test this scenario.  I look forward to your feedback.

**Comment by guydavis** [comment]
Following up on our Discord conversation to [scale Machinaris](https://github.com/guydavis/machinaris/wiki/Scaling#full-nodes) for your very large farm, we discussed disabling Forktools in your `docker-compose.yml` to optimize the first 15-30 minutes after container launch against more than 1000000 plots.

Suggested environment variables:
```
            - bladebit_skip_build=true
            - madmax_skip_build=true
            - forktools_skip_build=true
            - plots_check_analyze_skip=true
```

**Comment by guydavis** [comment]
Based on Discord discussions with @grobalt, the improvements in Machinaris v0.8.4, combined with the [Scaling guidance](https://github.com/guydavis/machinaris/wiki/Scaling), seem to have addressed the issue.  Thanks for the assistance in making Machinaris run better on such a huge farm!

**Comment by maxcom99** [comment]
this is amazing! went from 30-ish min to literally 2min to start now! thank you!!
