### ISSUE TITLE
add option for https of web console

### ISSUE THREAD

**Issue by technickal1** [guydavis/machinaris#80]
use https on web console with login to protect and use externally

**Comment by guydavis** [comment]
Good day!  Good suggestion, however the best place to control access to Machinaris is via an [authenticated](https://github.com/guydavis/machinaris/wiki/FAQ#security) web proxy such as [Nginx](https://github.com/guydavis/machinaris/wiki/Nginx) using SSL.  Since each user will have their own preferred proxy and authentication, it's best that Machinaris not force a particular solution on users.  Please the linked Wiki pages for details.
