### ISSUE TITLE
Queue given amount of plots

### ISSUE THREAD

**Issue by cani1989** [guydavis/machinaris#95]
Give Plotman a number of plots to make. 

For example, if I have a new 4TB disk, then I know I can only make around 40 plots.

**Comment by guydavis** [comment]
Hi, take a look at the improved [Archiving](https://github.com/ericaltendorf/plotman/wiki/Archiving) functionality now available via Plotman which will [distribute completed plots](https://github.com/ericaltendorf/plotman/issues/671) amongst a set of final drives based on their free space.

**Comment by guydavis** [comment]
Yes, I've looked more into this issue and found that Plotman simply isn't designed to have X number of plots created by a single plotter (chia/madmax) invocation.  This is due to Plotman's roots as a plot manager, wanting to manage each plot creation.  So, recommendation remains to use the archiving functionality which does take into account free space.
